### ISSUE TITLE
Cannot exclude annotations from serializer specs

### ISSUE THREAD

**Issue by JordanFinch72** [drwl/annotaterb#103]
## Problem

In the config, when `exclude_tests` is `true` but `exclude_serializers` is `false`, you still end up with annotations for the specs of serializers when the Rake task runs. I don't know if this is intentional, but for our codebase we gain little from having annotations in our serializers. Likewise, we lose little from having annotations in our serializers, so it's by no means an urgent request.

## Version

- annotaterb version 4.6.0
- rails version 7.0.8.1
- ruby version 3.2.2

## Config

```yaml
---
:position: after
:classified_sort: true
:exclude_controllers: true
:exclude_factories: false
:exclude_fixtures: false
:exclude_helpers: true
:exclude_scaffolds: true
:exclude_serializers: false
:exclude_sti_subclasses: false
:exclude_tests: true
:force: false
:format_markdown: false
:format_rdoc: false
:format_yard: false
:frozen: false
:ignore_model_sub_dir: false
:ignore_unknown_models: false
:include_version: false
:show_complete_foreign_keys: false
:show_foreign_keys: true
:show_indexes: true
:simple_indexes: false
:sort: false
:timestamp: false
:trace: false
:with_comment: true
:with_column_comments: true
:with_table_comments: true
:active_admin: false
:command: 
:debug: false
:hide_default_column_types: ''
:hide_limit_column_types: ''
:ignore_columns: 
:ignore_routes: 
:models: true
:routes: false
:skip_on_db_migrate: false
:target_action: :do_annotations
:wrapper: 
:wrapper_close: 
:wrapper_open: 
:additional_file_patterns: []
:model_dir:
- app/models
:require: []
:root_dir:
- ''
```

**Comment by JordanFinch72** [comment]
Much love for your continued work on this project, by the way. Such a simple thing and yet so useful!

**Comment by drwl** [comment]
@JordanFinch72 thanks for reporting. This may be a bug, but so I can better understand could you provide the app directory structure?

Something like this:
```
/app/models/
/app/namespace/models/
/spec/models/
/spec/fabricators/
/spec/namespace/models/
/spec/namespace/fabricators/
```

And potentially include a serializer related file that ideally gets annotated and another file that should not get annotated?

**Comment by JordanFinch72** [comment]
@drwl Here's the directory structure. It's fairly typical:

```
/app/models/
/app/serializers/
/spec/models/
/spec/serializers/
```

I suspect the issue lies [here](https://github.com/drwl/annotaterb/blob/a7796276f9b956174a1d6f340b974bde8af34170/lib/annotate_rb/model_annotator/related_files_list_builder.rb#L23) and [here](https://github.com/drwl/annotaterb/blob/main/lib/annotate_rb/model_annotator/pattern_getter.rb#L5). The `exclude_tests` option seems to only exclude model tests, while at the same time `!exclude_serializers` will include all serializer-related files, including the tests. Perhaps this is intended behaviour?

If not, maybe an option to opt out of serializer (and controller, too?) tests could be an idea? :)

**Comment by drwl** [comment]
Sorry for the delay, I've been preparing for interviews and haven't been prioritizing this. 

Got it -- you're indeed correct that there's some overlap in those options. It's "intended" in the sense that is the same behavior from the old gem. 

Right now, I'm leaning on keeping the configuration the same and to have `exclude_tests` option take precedence over any of the non-exclusion options. So for example, if you have `exclude_tests` and `!exclude_serializers` then it will only annotate serializers but not their tests. Additionally, if `exclude_tests` and `!exclude_scaffolds` then it will not annotate the controller tests. The tradeoff here is being able to keep the configuration options the same but adding some complexity. Thoughts?

**Comment by JordanFinch72** [comment]
I think that's a decent solution, although I think that if you plot a matrix of annotations and tests for all of the different annotateables, you wouldn't be able to have any combination that you wanted with this solution. For example, it wouldn't be possible to exclude tests for just serializers, right? 

I would propose either an array on `exclude_tests`, like:

```yaml
:exclude_tests: [:serializers, :controllers]
:exclude_controllers: false
:exclude_models: false
:exclude_serializers: false
```

With the above solution, you can continue to allow `:exclude_tests: true` such that it continues to handle it the way that it does right now. This ensures backwards-compatibility with projects already using the gem.

You could possibly also just expand the options to include more precise exclusions but without the array, like:

```yaml
:exclude_tests: false
:exclude_controllers: false
:exclude_controller_tests: false
:exclude_models: false
:exclude_model_tests: false
:exclude_serializers: false
:exclude_serializer_tests: true
```

Where `:exclude_tests: <value>` will override any undefined value in the config, so if it's `true` and you haven't specified `exclude_serialzer_tests: false`, then it would include them. _This whole "excludes false" instead of "includes true" thing really breaks my brain sometimes :')_.

Good luck with your interviews!

**Comment by drwl** [comment]
I think the suggestion around `exclude_tests` taking an array or boolean seems really good. I'll try tinkering with something this coming week. Ideally, I'd have more data on how this gem is being used (with what configurations / Rails project structure) and by whom and could make better design choices that way.

re: the original thought of `exclude_tests` && `!exclude_serializers`, I was looking at how the paths get built in `FilePatterns`. My understanding was that it's actually only the serializers and scaffolds that glob test directories. There's things like fixtures (which I haven't really in depth), factories, etc but those naturally live in test directories. 

With this said, a lot of the logic is from the old gem. There's probably a better way to answer the question "which files to annotated?" but I'll probably wait for more input + help to answer that question.

**Comment by JordanFinch72** [comment]
Yeah, it must be tricky to try to maintain/develop this in a vacuum. I've always used it as a cheap-and-easy way to see the data structure of my database models without having to, say, open up the database viewer in RubyMine or Postico. It could potentially also satisfy some developers' needs for type definitions in Ruby/Rails.

The reason against having the annotations in serializers' test files is that we already smoke test to see if all of the attributes that we want to send are being sent, and if any that we don't are - so the annotation doesn't help much. But it also doesn't harm us by it being there, and I'm always of the mindset that what doesn't harm you might help others.

Redeveloping the gem slightly might be an idea, but I'd definitely mark it with a major version - I don't know how many projects use this gem, but it would be annoying to have to reconfigure. Maybe the update could come with a Rake task to convert current config to new config? If it's possible.

**Comment by drwl** [comment]
@JordanFinch72 I made some potential changes here https://github.com/drwl/annotaterb/pull/107. Please read the description as it might vary a bit from what we talked about. If you can test it out and let me know if you have any feedback that would be great.

In making those changes, I found the developer ergonomics for managing what files to get annotated pretty bad, so this can definitely be an area to improve on for a future version.

**Comment by JordanFinch72** [comment]
Thanks, @drwl. I'll take a look as soon as I'm able!

**Comment by drwl** [comment]
I just pushed 4.8.0 to Rubygems and it should resolve this issue. Feel free to reopen if the issue isn't resolved.
