### ISSUE TITLE
Check constraint support

### ISSUE THREAD

**Issue by azz** [drwl/annotaterb#104]
Hey there. We currently use `annotate_models`, looking at maybe switching over, but it seems this fork does not support annotating check constraints. https://github.com/ctran/annotate_models/pull/868

@drwl would you be keen to see a similar implementation here?

**Comment by drwl** [comment]
@azz thanks for the issue! I added a PR, could you try building that version of the gem and tell me if it works and if you have any feedback?

**Comment by lparry** [comment]
Hey @drwl, I'm a colleague of @azz, I've had a quick play switching from `ctran/annotate_models` to `annotaterb` just now and can confirm that the check constraint annotations appear to work correctly/the same as what we are used to.

There are some other unexpected changes unrelated to check constraints, but is probably down to config we just need to tweak. I will open an issue about the one that has me a bit stumped.

**Comment by drwl** [comment]
@lparry thanks for taking the time to test it and providing feedback. I'm planning to add some unit tests and merging it in.
