### ISSUE TITLE
Nested module models and unexpected annotations

### ISSUE THREAD

**Issue by lparry** [drwl/annotaterb#106]
Hi, I'm seeing some odd behaviour for a model nested inside a name space with annotations previously generated by `annotate_models`

eg, we have (roughly, excuse any errors anonymising stuff)

```ruby
# == Schema Information
#
# Table name: my_models
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#
# Indexes
#
#  index_my_models_on_name  (name) UNIQUE
module MyModule
  # a long comment
  # over a few lines
  # more explanation
  class MyModel < ApplicationModel
  end
end
```

after running `annotaterb` I end up with a duplicate index + newline like this:

```ruby
# == Schema Information
#
# Table name: my_models
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#
# Indexes
#
#  index_my_models_on_name  (name) UNIQUE
#
#  index_my_models_on_name  (name) UNIQUE
module MyModule
  # a long comment
  # over a few lines
  # more explanation
  class MyModel < ApplicationModel
  end
end
```

removing the annotations and starting from scratch letting annotaterb pick where it thinks they belong, I end up with

```ruby
module MyModule
  # a long comment
  # over a few lines
# == Schema Information
#
# Table name: my_models
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#
# Indexes
#
#  index_my_models_on_name  (name) UNIQUE
  # more explanation
  class MyModel < ApplicationModel
  end
end
```

with the annotations inserted midway through the comment, and with an outdent as above. Any pointers which config options might help here?

**Comment by drwl** [comment]
@lparry thanks for reporting. I'll try and play around with this locally and see what's going on. I suspect the change in behavior is related to changes made for identifying the model annotations, done here https://github.com/drwl/annotaterb/pull/72

In short, I changed from using a regex to identify annotation comment block to using Ripper (Ruby file parser) to improve it. The additional indexes line seems interesting though.

**Comment by drwl** [comment]
@lparry just checking - is the actual annotation formatted like that? I think there should be an empty comment line break after the index and I believe it should look like:

```ruby
# == Schema Information
#
# Table name: my_models
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#
# Indexes
#
#  index_my_models_on_name  (name) UNIQUE
# 
module MyModule
  # a long comment
  # over a few lines
  # more explanation
  class MyModel < ApplicationModel
  end
end
```

I'm able to reproduce the issue using the annotation you have (with the missing comment line break) but I think that's not expected with this gem.

**Comment by drwl** [comment]
@lparry just checking in, was this able to be resolved on your side?

**Comment by yskkin** [comment]
I have same issue.
A model class nested in parent module gives annotation whose indent is wrong.
