### ISSUE TITLE
Duplicate content in fixtures when annotating models

### ISSUE THREAD

**Issue by ThibautGrx** [drwl/annotaterb#108]
When I annotate models, the content of fixture is duplicated. It's working fine for model and model test files.

![image](https://github.com/drwl/annotaterb/assets/35230028/cc4ea764-cc77-4e13-8744-4ef30148f489)

Here is my config:

```
---
:position: before
:position_in_additional_file_patterns: before
:position_in_class: before
:position_in_factory: before
:position_in_fixture: before
:position_in_routes: before
:position_in_serializer: before
:position_in_test: before
:classified_sort: true
:exclude_controllers: true
:exclude_factories: false
:exclude_fixtures: false
:exclude_helpers: true
:exclude_scaffolds: true
:exclude_serializers: false
:exclude_sti_subclasses: false
:exclude_tests: false
:force: false
:format_markdown: false
:format_rdoc: false
:format_yard: false
:frozen: false
:ignore_model_sub_dir: false
:ignore_unknown_models: false
:include_version: false
:show_complete_foreign_keys: false
:show_foreign_keys: true
:show_indexes: true
:simple_indexes: false
:sort: false
:timestamp: false
:trace: false
:with_comment: true
:with_column_comments: true
:with_table_comments: true
:active_admin: false
:command: 
:debug: false
:hide_default_column_types: ''
:hide_limit_column_types: ''
:ignore_columns: 
:ignore_routes: 
:models: true
:routes: false
:skip_on_db_migrate: false
:target_action: :do_annotations
:wrapper: 
:wrapper_close: 
:wrapper_open: 
:classes_default_to_s: []
:additional_file_patterns: []
:model_dir:
- app/models
:require: []
:root_dir:
- ''
```

## Commands

```
$ bundle exec annotaterb models
```

## Version

- annotaterb version 4.7.0
- rails version main
- ruby version 3.3.0

**Comment by drwl** [comment]
@ThibautGrx thanks for reporting, I was able to reproduce this on my end. This is definitely a bug — the new annotation finder and parser is a Ruby file parser and so doesn't support non-Ruby files. Will need to add a different file parser to support this.

I'll try to get to this after the other issue #106

**Comment by drwl** [comment]
@ThibautGrx sorry for the delay, I was preoccupied with preparing for interviews. I had time today to look into this, would you mind trying this branch of the gem? 

https://github.com/drwl/annotaterb/pull/110

I tested it locally using one fixture file and didn't have issues but it's nice to get extra testing before merging.

**Comment by drwl** [comment]
I just pushed 4.8.0 to Rubygems and it should resolve this issue. Feel free to reopen if the issue isn't resolved.
